version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
      # Use official MongoDB without auth to keep CI simple
      - image: mongo:6.0
        command: ["--bind_ip_all"]
    working_directory: ~/project

commands:
  wait-for-http:
    description: "Wait for an HTTP endpoint to return 200"
    parameters:
      url:
        type: string
      attempts:
        type: integer
        default: 90
      sleep_secs:
        type: integer
        default: 2
      log_path:
        type: string
        default: ""
    steps:
      - run:
          name: "Wait for << parameters.url >>"
          command: |
            set +e
            for i in $(seq 1 << parameters.attempts >>); do
              STATUS=$(curl -s -o /dev/null -w "%{http_code}" "<< parameters.url >>" || true)
              if [ "$STATUS" = "200" ]; then
                echo "Endpoint is up (HTTP 200)"; exit 0
              fi
              echo "Waiting for service (got $STATUS)… attempt $i/<< parameters.attempts >>"
              sleep << parameters.sleep_secs >>
            done
            echo "Service did not become ready in time."
            if [ -n "<< parameters.log_path >>" ] && [ -f "<< parameters.log_path >>" ]; then
              echo "==== API LOGS (tail) ===="
              tail -n 300 "<< parameters.log_path >>"
              echo "========================="
            fi
            exit 1

jobs:
  install-backend-deps:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-backend-deps-{{ checksum "secure-banking-backend/package-lock.json" }}
            - v1-backend-deps-
      - run:
          name: Install backend deps
          command: npm ci --prefix ./secure-banking-backend
      - save_cache:
          paths:
            - ./secure-banking-backend/node_modules
          key: v1-backend-deps-{{ checksum "secure-banking-backend/package-lock.json" }}

  test-backend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-backend-deps-{{ checksum "secure-banking-backend/package-lock.json" }}
            - v1-backend-deps-
      - run:
          name: Run backend tests
          command: npm test --prefix ./secure-banking-backend

  # Newman API tests against /secure-banking-backend/tests collection/env
  api-tests-newman:
    executor: node-executor
    environment:
      PORT: "8080"
      # No-auth Mongo service container above; app connects directly:
      MONGO_URI: "mongodb://localhost:27017/secure_banking"
      NODE_ENV: "test"
      JWT_SECRET: "ci-secret-jwt"
      FIELD_ENCRYPTION_KEY: "ci-field-encryption-key"
      PEPPER: "ci-pepper"
      CORS_ORIGIN: "http://localhost:5173"
      BCRYPT_COST: "10"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-backend-deps-{{ checksum "secure-banking-backend/package-lock.json" }}
            - v1-backend-deps-
      - run:
          name: Start API (background, capture logs)
          command: |
            cd secure-banking-backend
            node src/server.js > ../api.log 2>&1 &
            echo $! > ../api.pid
      - wait-for-http:
          url: "http://127.0.0.1:8080/api/health"
          attempts: 90
          sleep_secs: 2
          log_path: "api.log"
      - run:
          name: Run Newman collection
          command: |
            cd secure-banking-backend
            npx newman run ./tests/SecureBanking.postman_collection.json \
              -e ./tests/SecureBanking.local_environment.json \
              --reporters cli \
              --bail
      - run:
          name: Stop API
          command: |
            if [ -f api.pid ]; then kill -9 $(cat api.pid) || true; fi
            sleep 1
            if [ -f api.log ]; then echo "==== FINAL API LOGS (tail) ===="; tail -n 200 api.log || true; fi

  install-frontend-deps:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-frontend-deps-{{ checksum "secure-banking-frontend/package-lock.json" }}
            - v1-frontend-deps-
      - run:
          name: Install frontend deps
          command: npm ci --prefix ./secure-banking-frontend
      - save_cache:
          paths:
            - ./secure-banking-frontend/node_modules
          key: v1-frontend-deps-{{ checksum "secure-banking-frontend/package-lock.json" }}

  build-frontend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-frontend-deps-{{ checksum "secure-banking-frontend/package-lock.json" }}
            - v1-frontend-deps-
      - run:
          name: Build frontend
          command: npm run build --prefix ./secure-banking-frontend

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-backend-deps
      - test-backend:
          requires:
            - install-backend-deps
      - api-tests-newman:
          requires:
            - install-backend-deps
      - install-frontend-deps
      - build-frontend:
          requires:
            - install-frontend-deps
