# .circleci/config.yml

version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
    working_directory: ~/project

jobs:
  install-deps:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          paths:
            - ~/.npm
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

  run-tests:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: Run backend tests
          command: npm test --prefix ./secure-banking-backend
      - run:
          name: Lint backend
          command: npm run lint --prefix ./secure-banking-backend

  start-server:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Start server
          command: |
            cd ./secure-banking-backend
            node src/server.js

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-deps
      - run-tests:
          requires:
            - install-deps