version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
    working_directory: ~/project

jobs:
  install-backend-deps:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-backend-deps-{{ checksum "secure-banking-backend/package-lock.json" }}
            - v1-backend-deps-
      - run:
          name: Install backend deps
          command: npm ci --prefix ./secure-banking-backend
      - save_cache:
          paths:
            - ./secure-banking-backend/node_modules
          key: v1-backend-deps-{{ checksum "secure-banking-backend/package-lock.json" }}

  test-backend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-backend-deps-{{ checksum "secure-banking-backend/package-lock.json" }}
            - v1-backend-deps-
      - run:
          name: Run backend tests
          command: npm test --prefix ./secure-banking-backend

  install-frontend-deps:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-frontend-deps-{{ checksum "secure-banking-frontend/package-lock.json" }}
            - v1-frontend-deps-
      - run:
          name: Install frontend deps
          command: npm ci --prefix ./secure-banking-frontend
      - save_cache:
          paths:
            - ./secure-banking-frontend/node_modules
          key: v1-frontend-deps-{{ checksum "secure-banking-frontend/package-lock.json" }}

  build-frontend:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-frontend-deps-{{ checksum "secure-banking-frontend/package-lock.json" }}
            - v1-frontend-deps-
      - run:
          name: Build frontend
          command: npm run build --prefix ./secure-banking-frontend

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-backend-deps
      - test-backend:
          requires:
            - install-backend-deps
      - install-frontend-deps
      - build-frontend:
          requires:
            - install-frontend-deps
